### ISSUE TITLE
[Bug] Download button in Module Select Doesn't work

### ISSUE THREAD

**Issue by cadowtin** [Saibot393/LocknKey#1]
![image](https://github.com/Saibot393/LocknKey/assets/79132112/e868d701-1ce1-4d1a-800c-da4075460707)

**Comment by cadowtin** [comment]
Release has no Zip

**Comment by Saibot393** [comment]
That is extremly strange, i have tested it on two pcs and both installs works correctly. Could you verify, that you can not download this file manually: https://github.com/Saibot393/LocknKey/archive/refs/tags/v1.0.0.zip

**Comment by Mesk62** [comment]
I can verify.  Won't install for me: 
![image](https://github.com/Saibot393/LocknKey/assets/43838083/5449441a-71ec-4fb2-aab4-f9183c05d582)

(Riboflavin here)  Nice fonts @cadowtin

**Comment by Saibot393** [comment]
The bug should now be sesolved. It it was caused by a wrongly named file. The strange thing is, that it appears to be a git/GitHub bug, since it was correctly named in my local repositroy (github didn't update the name in the public main branch). Even stranger is the fact that the wrongly named file did seem to work for at least a few installations (all i localy tested). Could be a strange JavaScript bug.
Thanks for the report, i would have never spotted that myself!
