### ISSUE TITLE
pf2e key/picklock not actually unlocking doors

### ISSUE THREAD

**Issue by Agyess1** [Saibot393/LocknKey#119]
Keys simply don't work. Pick lock brings up the proper roll and the chat identifies success/failure but doesn't change the the lock state.
Everything is upto date and current release:
![image](https://github.com/user-attachments/assets/9a350f19-af23-4688-a189-1930ae85345c)

**Comment by Saibot393** [comment]
From the error messages it seems like you were testing the lock picking while being logged in as a player but without having a gm logged in. Most features of Lock & Key require a GM account to be logged in (which is the case for many modules). The reason is, that in core foundry it is impossible for players to change certain door states. To allow players to have a certain access to this data, Lock & Key basically makes the GM account do the required changes.

**Comment by Agyess1** [comment]
did not realize that was an issue. Thank you!

**Comment by Saibot393** [comment]
You are welcome
