### ISSUE TITLE
Pickpocket Items aren't removed from target

### ISSUE THREAD

**Issue by fedeicodip** [Saibot393/LocknKey#124]
Hi Saibot, I notice that the pickpocket from npc don't take the loot from target tokens. I mean items are not removed from original target but just copied to the player inventory. Can you check it this is also the case for you? I updated to foundry vs 12 and dnd 4.1

**Comment by Saibot393** [comment]
So, to me everything seems to work as intended. It is however true, that the items will only be set to quantity 0 and will not be removed. This is basically done as a precaution, so that if a player accidentally loots an item that was not supposed to be lootable, fixing that is a bit easier.
I can however add a setting, so that items that are looted down to quantity 0 are removed

**Comment by fedeicodip** [comment]
Hi Saibot, I will give a check. Maybe it was me not paying enough attention. Thank you for checking

**Comment by Saibot393** [comment]
I will look into that bug, should (hopefully) be relatively easy to patch.

**Comment by Saibot393** [comment]
I have released a fix with v3.1.11. Looted containers should now be deleted

**Comment by fedeicodip** [comment]
I really appreciate how you work and active maintain these modules. Also you are very nice in keeping us updated on changes.
Can I help you somehow with a patreon support or anything else? Let me know please
Kind regards
Federico

**Comment by Saibot393** [comment]
Happy to hear that the work is appreciated. 
No, i don't have a patreon or similar, thanks for the offer though

**Comment by fedeicodip** [comment]
If you plan on opening such things in the future, I'll remember your kindness. Thanks again
