### ISSUE TITLE
Use Replacement Picks instead of destroying Thieves Tools [pf2e]

### ISSUE THREAD

**Issue by Peach774** [Saibot393/LocknKey#30]
If you are using the lockpick breaking rules, which are how pf2e normally works, on a critical fail, your lockpick is supposed to break. Unfortunately, this system removes the thieves tools from the user's inventory, which makes repairing them with a replacement pick difficult, and usually leaves it up to the GM to re-add the item to their inventory. If there was detection of replacement picks so that they would be consumed instead of the thieves tools breaking, that would be a great feature/improvement.

**Comment by Saibot393** [comment]
I will look into this for the next release. 
I will probably add a "replacement" field to item settings where ids/names of items can be entered that should (if present) be consumed instead of this item.
I will probably also use the opportunity to add a compendium with a few preconfigured items relating to lock & key.

**Comment by Saibot393** [comment]
I have added a new field "Replacement items" for items that get consumed instaed when a roll fails to the item settings with v1.10.0.

**Comment by Peach774** [comment]
I don't see the option for this in the lock n key settings.
