### ISSUE TITLE
LocknKey module breaks "Scale" setting for Item piles tokens.

### ISSUE THREAD

**Issue by Hevkalo1** [Saibot393/LocknKey#40]
System : pf1 v.9.4
Foundry v 11.313
modules : Item piles 2.7.16 , LocknKey 1.10.7

What's wrong : Scale setting for item piles tokens keeps reseting to bizzare number if you try to change it.

Additional info :
![image](https://github.com/Saibot393/LocknKey/assets/148167540/757bf80b-4932-440c-bd00-6e6367d27015)

**Comment by Saibot393** [comment]
Thanks for informing me, i will have a look at it.

**Comment by Saibot393** [comment]
I could not recreate this behaviour. Could you send me screenshots of both the Lock & Key token settings and the Item Piles setting of a token with this behaviour?
This behaviour is quite unexpected since Lock & Key doesn't have any influence on a tokens scalling, do you have any other modules active that could affect the scaling of tokens? There could be some strange cross module behaviour at play here.

**Comment by Hevkalo1** [comment]
![image](https://github.com/Saibot393/LocknKey/assets/148167540/73f3e98c-1abc-400d-980c-0eac60fc0d13)
![image](https://github.com/Saibot393/LocknKey/assets/148167540/2f5d0ca1-ad01-4b1c-b5b1-67c1840652b5)
![image](https://github.com/Saibot393/LocknKey/assets/148167540/5d552fa9-0bed-48bd-ad8d-a8b35f9f6acd)
![image](https://github.com/Saibot393/LocknKey/assets/148167540/5ce9c21c-187b-4b55-ae7b-a723837ff83f)
![image](https://github.com/Saibot393/LocknKey/assets/148167540/3821d912-84a7-4449-81b0-ee0f170506e3)
No modules are active besides them and dependencies.

**Comment by Hevkalo1** [comment]
it is working as intended now.

**Comment by Saibot393** [comment]
good to hear
