### ISSUE TITLE
Receiving Libwrapper warning with Monk's Enhanced Journals and Lock & Key enabled

### ISSUE THREAD

**Issue by devteamplus** [Saibot393/LocknKey#5]
I have the latest "Monk's Enhanced Journals" module installed.  After enabling "Lock & Key" I'm receiving this warning:

```
LibWrapper: module Monk's Enhanced Journal and module Lock & Key modify the same FoundryVTT functionality and are more likely to conflict. (See JS Console)
fetch @ foundry.js:68050
```

**Comment by Saibot393** [comment]
I am not too familiar with Monk's Enhanced Journal but after a bit of testing i have so far not found any problems. I would guess, that the libwrapper warning is only there because in theory the control sceme of the modules could clash(left/right click on tokens or doors). In practice however i can not really think of a situation where this would matter, though i dont know all functions of Monk's Enhanced Journal. 
Should any actual problems arise or if you know of any control scemes that actually clash please add them to this issue.

**Comment by devteamplus** [comment]
Will do.  Thanks.
